### ISSUE TITLE
Scale down not getting all runners for org

### ISSUE THREAD

**Issue by mcaulifn** [philips-labs/terraform-aws-github-runner#1151]
The pagination [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/ba2536bbf7bc7a98180b25d8703ef6edc25bc2b7/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L58) is not working correctly for getting all runners for an org. If there are more than 30, the full list is not fetched. I confirmed that this works with this code:

```typescript
import { Octokit } from '@octokit/rest';

async function getRunners(owner: string): Promise<any> {
  const octokit = new Octokit({
    auth: 'xxx',
    baseUrl: 'https://github.local/api/v3',
  });
  return await octokit.paginate(octokit.actions.listSelfHostedRunnersForOrg, {
    org: owner,
  });
}

async function run(): Promise<void> {
  console.log(await getRunners('org-name'));
}

run();
```

**Comment by bjorntheart** [comment]
_30_ results is standard behaviour according the the [pagination docs](octokit.actions.listSelfHostedRunnersForOr). 
Aren't you missing a `.then()` block?
```js
async function run(): Promise<void> {  
  // console.log(await getRunners('org-name'));
  await getRunners('org-name').then((runners) => console.log(runners))
}
```

**Comment by bjorntheart** [comment]
wait... I just saw your open PR https://github.com/philips-labs/terraform-aws-github-runner/pull/1164. Is your question here still relevant? :-)

**Comment by mcaulifn** [comment]
The 30 results per page is expected if just calling the endpoint without `octokit.paginate`. Looking at the [code](https://github.com/octokit/plugin-paginate-rest.js/blob/694d3611fbe21b8eb4fb0a26dc5574c09d5c3536/src/paginate.ts#L23), I read it as the entire set of results should be gathered before the promise is resolved. 

I would have expected [this](https://github.com/philips-labs/terraform-aws-github-runner/blob/ba2536bbf7bc7a98180b25d8703ef6edc25bc2b7/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L58) to also be properly awaited but it didn't appear to be in my local testing.

The PR is for a different issue where subsequent Lambda runs can retain data in memory. Because of that, the class still has data from previous runs.

**Comment by npalm** [comment]
@mcaulifn So scale down is not working over 30+ runners? We haven't seen an issue over the last month wit a larger set of runners.

**Comment by mcaulifn** [comment]
I am not seeing this consistently. I'll close this for now and re-open if we see it again.

**Comment by maschwenk** [comment]
We're seeing a similar issue. We run 500+ runners routinely, so if the pagination was broken it would really cause chaos. However, it seems like we're still seeing situations where Runners are missing from the data that Github provides. If it was inconsistent for @mcaulifn I wonder if there's a chance this is actually an API bug on Github's side? 

We're having cases where we can see a Job clearly in the middle executing on a Runner, seeing the logs of the scale down attempt to do the hard termination (e.g. not bothering to de-register first). I wonder if, in that unhappy path of termination without de-registering we should *re* query Github to double check it's not there?

**Comment by andrewdibiasio6** [comment]
Should this be re-opened? We hit this issue often, and we have hundreds of runners often.


```{
    "level": "INFO",
    "message": "Runner 'i-0010112d6c39eddc2' is orphaned and will be removed.",
    "service": "runners-scale-down",
    "timestamp": "2024-06-13T18:30:39.363Z",
    "module": "scale-down",
    ...
}

**Comment by mrmeyers99** [comment]
We're also seeing this issue fairly frequently.

**Comment by mrmeyers99** [comment]
Can we get this issue re-opened?  We are seeing it very consistently.
