### ISSUE TITLE
webhook.zip file triggers trojan alert in Windows 10

### ISSUE THREAD

**Issue by mrchief** [philips-labs/terraform-aws-github-runner#954]
Downloading latest webhook.zip file from releases triggers a Trojan alert and Windows automatically removes the file

![image](https://user-images.githubusercontent.com/781818/124370017-4b0b9500-dc40-11eb-8745-074f5ac0a080.png)

OS: Microsoft Windows [Version 10.0.19042.1052] 64bit

File in question: https://github.com/philips-labs/terraform-aws-github-runner/releases/download/v0.14.0/webhook.zip

**Comment by npalm** [comment]
@gertjanmaas can you run a check on you windows machine as well?

**Comment by ScottGuymer** [comment]
Is this from a specific malware tool or Windows defender?

I am not seeing this on my Windows machine although I'm on an older 1803 build.

**Comment by mrchief** [comment]
> Is this from a specific malware tool or Windows defender?

@ScottGuymer Just Windows Defender

**Comment by gertjanmaas** [comment]
Seeing the same error message from Windows Defender on my home PC, different TrojanScript though:

![image](https://user-images.githubusercontent.com/2847704/124734218-3287cd00-df15-11eb-8937-1883c23767ec.png)

Version: Windows 10 Pro (21H1) 19043.1052

**Comment by npalm** [comment]
Looking for suggestion how we can solve this, any idea?

**Comment by ScottGuymer** [comment]
My initial thought would be to not zip up the js file..

I have started up a new W10 VM to give this a test on to see if I can replicate it and test some alternatives..

**Comment by npalm** [comment]
We created the zip files since this is the default way of delivery a lambda artifact. Another option would be to publish to a public S3 bucktet. But this first requires approvals in our organizaiton.

**Comment by ScottGuymer** [comment]
@mrchief @gertjanmaas how are you downloading this file? Using the mechanism in the terraform code, manually in the browser, via powershell or something else?

**Comment by gertjanmaas** [comment]
> @mrchief @gertjanmaas how are you downloading this file? Using the mechanism in the terraform code, manually in the browser, via powershell or something else?

This was just via the link in a browser. Google said it failed due to security scan or something similar.

**Comment by mcaulifn** [comment]
I tried two different Windows laptops. My personal one does not allow it, my work one does. Has anyone tried building the zip manually from tag `v0.14.0` to see if the resulting zip file has the same results?

**Comment by ScottGuymer** [comment]
I cant seem to replicate this on this VM. Tried downloading with powershell/edge/chrome etc..

![image](https://user-images.githubusercontent.com/956825/124758972-6a037300-df2f-11eb-899e-e6bfa5e40ca9.png)

**Comment by gertjanmaas** [comment]
Seems it is resolved on my home PC by updating the definitions.

Under Windows Security -> Virus & Threat Protection -> Check for updates:
I was on 1.343.547.0, pressed the update button, now I'm at 1.343.553.0 and I can download the zip file.

@mrchief can you confirm this works?

Also submitted a false positive to Microsoft ( via https://www.microsoft.com/en-us/wdsi/filesubmission ). Not sure if that has any effect.

**Comment by ScottGuymer** [comment]
I had made sure my definitions were up to date, so maybe this is just a false positive that has already been dealt with.

**Comment by mrchief** [comment]
I am on 1.343.521.0 and and I hit manual update so now I'm on 573.
![image](https://user-images.githubusercontent.com/781818/124812510-b3ed5880-df31-11eb-9966-0d6c35f69082.png)

https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Wacatac.B!ml&threatid=2147735503

I clicked on 0.15.0 and I still get the warning
![image](https://user-images.githubusercontent.com/781818/124812463-a506a600-df31-11eb-8c33-b11e7b24ccfd.png)

I no longer get the warning on 0.14.0 but that is probably due to the fact that I explicitly allowed it in defender. 

It's very much a false positive because I checked with virustotal and everything was green. Thanks for reporting that to MS.

**Comment by npalm** [comment]
Looks like we can close this issue

**Comment by gertjanmaas** [comment]
Nope, still an issue with 0.15.0 and 0.15.1

**Comment by npalm** [comment]
Is this still an issue?

**Comment by npalm** [comment]
Thanks for reporting, due to no activity I close the issue. Please feel free to re-open.
